"""
Django settings for ith_proxy project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-g^!q6b8ibco$5x%6x2d)v(tl-=ff+2$bowq+*ze$55)o_dp2kp')

# Encryption key for PHI data (use environment variable in production)
# ENCRYPTION_KEY should be set via environment variable in production
# If not set, will derive from SECRET_KEY (development only)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'channels',
    'receiver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ith_proxy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'receiver' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ith_proxy.wsgi.application'
ASGI_APPLICATION = 'ith_proxy.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database configuration supports both SQLite and PostgreSQL
# Set DATABASE_ENGINE environment variable to 'postgresql' to use PostgreSQL
DATABASE_ENGINE = os.getenv('DATABASE_ENGINE', 'sqlite').lower()

if DATABASE_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'ith_proxy'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
else:
    # Default to SQLite
    sqlite_path = os.getenv('DATABASE_PATH', str(BASE_DIR / 'storage' / 'database' / 'db.sqlite3'))
    # Create database directory if it doesn't exist
    Path(sqlite_path).parent.mkdir(parents=True, exist_ok=True)

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_path,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'en-us')

TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# DICOM Receiver Settings
# =============================================================================

# DICOM Network Configuration
DICOM_AE_TITLE = os.getenv('DICOM_AE_TITLE', 'DICOMRCV')
DICOM_PORT = int(os.getenv('DICOM_PORT', '11112'))
DICOM_BIND_ADDRESS = os.getenv('DICOM_BIND_ADDRESS', '')  # Empty = bind to all interfaces

# Storage Configuration
DICOM_STORAGE_DIR = os.getenv('DICOM_STORAGE_DIR', str(BASE_DIR / 'storage'))

# Study Completion Configuration
DICOM_STUDY_TIMEOUT = int(os.getenv('DICOM_STUDY_TIMEOUT', '60'))  # seconds

# DICOM Protocol Configuration
DICOM_MAX_PDU_SIZE = int(os.getenv('DICOM_MAX_PDU_SIZE', '16384'))  # bytes
DICOM_ACSE_TIMEOUT = int(os.getenv('DICOM_ACSE_TIMEOUT', '30'))  # seconds
DICOM_MAX_ASSOCIATIONS = int(os.getenv('DICOM_MAX_ASSOCIATIONS', '50'))

# Logging Configuration
DICOM_LOG_LEVEL = os.getenv('DICOM_LOG_LEVEL', 'INFO')
DICOM_LOG_DIR = os.getenv('DICOM_LOG_DIR', str(BASE_DIR / 'storage' / 'logs'))

# Create logs directory if it doesn't exist
Path(DICOM_LOG_DIR).mkdir(parents=True, exist_ok=True)

# PHI Anonymization
DICOM_ANONYMIZE_PATIENTS = os.getenv('DICOM_ANONYMIZE_PATIENTS', 'True').lower() == 'true'

# Auto-start DICOM server with Django
DICOM_AUTO_START = os.getenv('DICOM_AUTO_START', 'True').lower() == 'true'

# Create storage directory if it doesn't exist
Path(DICOM_STORAGE_DIR).mkdir(parents=True, exist_ok=True)

# =============================================================================
# Study Archive & Upload Configuration
# =============================================================================

# Archive directory for ZIP files
ARCHIVE_DIR = os.getenv('ARCHIVE_DIR', str(BASE_DIR / 'storage' / 'archives'))

# Create archive directory if it doesn't exist
Path(ARCHIVE_DIR).mkdir(parents=True, exist_ok=True)

# Upload retry settings
UPLOAD_MAX_RETRIES = int(os.getenv('UPLOAD_MAX_RETRIES', '3'))
UPLOAD_RETRY_DELAY = int(os.getenv('UPLOAD_RETRY_DELAY', '5'))

# Cleanup after successful upload (delete original DICOM files)
CLEANUP_AFTER_UPLOAD = os.getenv('CLEANUP_AFTER_UPLOAD', 'False').lower() == 'true'

# =============================================================================
# Logging Configuration
# =============================================================================

# Import the logging configuration
from receiver.utils.logging_config import get_logging_config
LOGGING = get_logging_config()

# =============================================================================
# Django REST Framework Settings
# =============================================================================

REST_FRAMEWORK = {
    # Use orjson for better performance
    'DEFAULT_RENDERER_CLASSES': [
        'receiver.utils.renderers.ORJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'receiver.utils.parsers.ORJSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    # Pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    # Authentication - Validates JWT tokens against ITH backend
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'receiver.guard.BackendTokenAuthentication',
    ],
    # Default permissions - require authentication for all endpoints
    # Individual views can override this with permission_classes
    'DEFAULT_PERMISSION_CLASSES': [
        'receiver.guard.IsAuthenticated',
    ],
    # Exception handling
    'UNAUTHENTICATED_USER': None,  # Return None for unauthenticated users
    'UNAUTHENTICATED_TOKEN': None,
}

# =============================================================================
# Django Channels Settings (WebSocket Support)
# =============================================================================

# Use in-memory channel layer for development (no Redis required)
# For production, use Redis backend for better performance and scalability
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    },
}

# Production Redis configuration (commented out by default)
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')],
#         },
#     },
# }

# =============================================================================
# ITH API Configuration
# =============================================================================

# ITH API Base URL
ITH_URL = os.getenv('ITH_URL', 'http://localhost:8000')

# Proxy Authentication Token (REQUIRED - get from ITH dashboard)
ITH_TOKEN = os.getenv('ITH_TOKEN', '')

# Proxy version
PROXY_VERSION = os.getenv('PROXY_VERSION', '1.0.0')
