# Generated by Django 4.2.25 on 2025-10-04 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import receiver.utils.fields.encrypted_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Server IP address (auto-detected)')),
                ('port', models.PositiveIntegerField(default=11112, help_text='DICOM SCP port (1024-65535)', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)])),
                ('ae_title', models.CharField(default='LAMINATE_PROXY', help_text='Application Entity Title (max 16 characters)', max_length=16)),
                ('resolver_api_url', models.URLField(blank=True, default='', help_text='PHI Resolver API URL (optional)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxy Configuration',
                'verbose_name_plural': 'Proxy Configuration',
                'db_table': 'proxy_configuration',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_id', models.CharField(db_index=True, max_length=255)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('study_time', models.TimeField(blank=True, null=True)),
                ('study_description', models.TextField(blank=True)),
                ('accession_number', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('uploaded', 'Uploaded'), ('archived', 'Archived')], default='incomplete', max_length=20)),
                ('last_received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('storage_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-last_received_at'],
                'indexes': [models.Index(fields=['study_instance_uid'], name='sessions_study_i_9c63c6_idx'), models.Index(fields=['patient_id'], name='sessions_patient_3c0008_idx'), models.Index(fields=['status'], name='sessions_status_2c94db_idx'), models.Index(fields=['-last_received_at'], name='sessions_last_re_7aa24a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_patient_name', receiver.utils.fields.encrypted_fields.EncryptedCharField(max_length=512)),
                ('original_patient_id', receiver.utils.fields.encrypted_fields.EncryptedCharField(max_length=512)),
                ('anonymous_patient_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('anonymous_patient_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('phi_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'patient_mappings',
                'indexes': [models.Index(fields=['anonymous_patient_name'], name='patient_map_anonymo_b49d66_idx'), models.Index(fields=['anonymous_patient_id'], name='patient_map_anonymo_f0d1e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('series_number', models.IntegerField(blank=True, null=True)),
                ('series_description', models.TextField(blank=True)),
                ('modality', models.CharField(blank=True, max_length=16)),
                ('storage_path', models.CharField(max_length=500)),
                ('instances_count', models.IntegerField(default=0)),
                ('instances_metadata_file', models.CharField(default='instances.xml', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='receiver.session')),
            ],
            options={
                'db_table': 'scans',
                'ordering': ['series_number'],
                'indexes': [models.Index(fields=['series_instance_uid'], name='scans_series__37ad51_idx'), models.Index(fields=['session'], name='scans_session_8f67b2_idx')],
            },
        ),
    ]
