# Generated by Django 4.2.25 on 2025-10-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyconfiguration',
            name='proxy_key',
            field=models.CharField(blank=True, default='', help_text='Laminate API Proxy Key (from dashboard)', max_length=256),
        ),
    ]
