# Generated by Django 4.2.25 on 2025-10-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='phi_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='session',
            name='phi_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
