# Generated by Django 4.2.25 on 2025-10-04 16:26

from django.db import migrations
import receiver.utils.fields.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_proxyconfiguration_proxy_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyconfiguration',
            name='proxy_key',
            field=receiver.utils.fields.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='Laminate API Proxy Key (from dashboard)', max_length=512),
        ),
    ]
