# Generated by Django 4.2.25 on 2025-10-31 16:54

from django.db import migrations


def redistribute_phi_metadata_forward(apps, schema_editor):
    """
    Redistribute PHI metadata from PatientMapping to Session and Scan tables.

    Strategy:
    - Patient-level: Keep in PatientMapping (PatientBirthDate, PatientSize, PatientWeight, PatientSex)
    - Study-level: Move to Session (StudyDate, StudyTime, StudyID, Institution/Physician info)
    - Series-level: Move to Scan (SeriesDate, SeriesTime, AcquisitionDate/Time, ContentDate/Time, DeviceSerialNumber)
    - PatientAge: REMOVE (redundant - can be calculated from PatientBirthDate + StudyDate)
    """
    PatientMapping = apps.get_model('receiver', 'PatientMapping')
    Session = apps.get_model('receiver', 'Session')
    Scan = apps.get_model('receiver', 'Scan')

    # Define field categories
    PATIENT_FIELDS = [
        'PatientBirthDate',
        'PatientSize',
        'PatientWeight',
        'PatientSex',
    ]

    STUDY_FIELDS = [
        'StudyDate',
        'StudyTime',
        'StudyID',
        'InstitutionName',
        'InstitutionAddress',
        'InstitutionalDepartmentName',
        'StationName',
        'ReferringPhysicianName',
        'ReferringPhysicianAddress',
        'ReferringPhysicianTelephoneNumbers',
        'PhysiciansOfRecord',
        'PerformingPhysicianName',
        'NameOfPhysiciansReadingStudy',
        'OperatorsName',
    ]

    SERIES_FIELDS = [
        'SeriesDate',
        'SeriesTime',
        'AcquisitionDate',
        'AcquisitionTime',
        'ContentDate',
        'ContentTime',
        'DeviceSerialNumber',
    ]

    # Fields to REMOVE (not store anywhere)
    REMOVED_FIELDS = [
        'PatientAge',  # Redundant - can be calculated from PatientBirthDate + StudyDate
    ]

    print("\n" + "=" * 80)
    print("DATA MIGRATION: Redistributing PHI Metadata")
    print("=" * 80)

    # Process each patient mapping
    total_mappings = PatientMapping.objects.count()
    print(f"\nProcessing {total_mappings} patient mapping(s)...")

    for idx, mapping in enumerate(PatientMapping.objects.all(), 1):
        print(f"\n[{idx}/{total_mappings}] Patient: {mapping.anonymous_patient_name}")

        # Get existing phi_metadata
        phi_data = mapping.phi_metadata or {}

        if not phi_data:
            print(f"  └─ No PHI metadata to redistribute")
            continue

        # Categorize PHI data
        patient_phi = {k: v for k, v in phi_data.items() if k in PATIENT_FIELDS}
        study_phi = {k: v for k, v in phi_data.items() if k in STUDY_FIELDS}
        series_phi = {k: v for k, v in phi_data.items() if k in SERIES_FIELDS}
        removed_data = {k: v for k, v in phi_data.items() if k in REMOVED_FIELDS}

        # Log what's being moved
        if patient_phi:
            print(f"  ├─ Patient-level: {len(patient_phi)} fields")
        if study_phi:
            print(f"  ├─ Study-level: {len(study_phi)} fields")
        if series_phi:
            print(f"  ├─ Series-level: {len(series_phi)} fields")
        if removed_data:
            print(f"  ├─ Removing: {', '.join(removed_data.keys())}")

        # Update PatientMapping to keep only patient-level data
        mapping.phi_metadata = patient_phi
        mapping.save(update_fields=['phi_metadata'])
        print(f"  ├─ Updated PatientMapping")

        # Find all sessions for this patient
        sessions = Session.objects.filter(patient_id=mapping.anonymous_patient_id)
        session_count = sessions.count()
        print(f"  ├─ Found {session_count} session(s)")

        for session in sessions:
            # Set study-level PHI metadata
            session.phi_metadata = study_phi
            session.save(update_fields=['phi_metadata'])

            # Find all scans for this session
            scans = Scan.objects.filter(session=session)
            scan_count = scans.count()

            for scan in scans:
                # Set series-level PHI metadata
                scan.phi_metadata = series_phi
                scan.save(update_fields=['phi_metadata'])

            print(f"  │  └─ Session {session.study_instance_uid[:40]}...: {scan_count} scan(s) updated")

        print(f"  └─ ✓ Complete")

    print("\n" + "=" * 80)
    print("DATA MIGRATION COMPLETE")
    print(f"Summary:")
    print(f"  - Patient mappings processed: {total_mappings}")
    print(f"  - Sessions updated: {Session.objects.count()}")
    print(f"  - Scans updated: {Scan.objects.count()}")
    print("=" * 80 + "\n")


def redistribute_phi_metadata_reverse(apps, schema_editor):
    """
    Reverse migration: consolidate all PHI metadata back into PatientMapping.
    """
    PatientMapping = apps.get_model('receiver', 'PatientMapping')
    Session = apps.get_model('receiver', 'Session')
    Scan = apps.get_model('receiver', 'Scan')

    print("\n" + "=" * 80)
    print("REVERSE MIGRATION: Consolidating PHI Metadata back to PatientMapping")
    print("=" * 80)

    for mapping in PatientMapping.objects.all():
        # Start with existing patient-level data
        consolidated_phi = dict(mapping.phi_metadata or {})

        # Get study-level data from any session for this patient
        session = Session.objects.filter(patient_id=mapping.anonymous_patient_id).first()
        if session and session.phi_metadata:
            consolidated_phi.update(session.phi_metadata)

        # Get series-level data from any scan for this patient
        if session:
            scan = Scan.objects.filter(session=session).first()
            if scan and scan.phi_metadata:
                consolidated_phi.update(scan.phi_metadata)

        # Update PatientMapping with consolidated data
        mapping.phi_metadata = consolidated_phi
        mapping.save(update_fields=['phi_metadata'])

        print(f"  ✓ Consolidated {mapping.anonymous_patient_name}")

    print("=" * 80 + "\n")


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_add_phi_metadata_to_session_and_scan'),
    ]

    operations = [
        migrations.RunPython(
            redistribute_phi_metadata_forward,
            reverse_code=redistribute_phi_metadata_reverse
        ),
    ]
