# Generated by Django 5.2.9 on 2026-01-07 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receiver", "0003_redistribute_phi_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="last_upload_attempt_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent upload attempt",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="last_upload_error",
            field=models.TextField(
                blank=True,
                help_text="Error message from the most recent failed upload attempt",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="upload_attempt_count",
            field=models.IntegerField(
                default=0, help_text="Total number of upload attempts made"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "Upload In Progress"),
                    ("success", "Upload Success"),
                    ("failed", "Upload Failed"),
                    ("pending_retry", "Pending Retry"),
                ],
                db_index=True,
                default="not_started",
                help_text="Status of upload to platform",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.IntegerField(
                        default=1,
                        help_text="Which attempt this is (1st, 2nd, 3rd auto-retry, or manual re-upload)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of this upload attempt",
                        max_length=20,
                    ),
                ),
                (
                    "api_response_id",
                    models.CharField(
                        blank=True,
                        help_text="Dataset ID returned from platform API on success",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "upload_file_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Size of uploaded file in bytes",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message from API or system (truncated to 500 chars)",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="HTTP status code (e.g., 401, 413, 500)",
                        max_length=50,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When upload attempt started",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When upload attempt completed (success or failure)",
                        null=True,
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="How long the upload took in seconds",
                        null=True,
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        blank=True,
                        help_text="Which chunk this is (for files > 2GB)",
                        null=True,
                    ),
                ),
                (
                    "total_chunks",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of chunks for this upload",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this log record was created"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The session/study being uploaded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_logs",
                        to="receiver.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upload Log",
                "verbose_name_plural": "Upload Logs",
                "db_table": "upload_logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "-started_at"],
                        name="upload_logs_session_def9d1_idx",
                    ),
                    models.Index(
                        fields=["status"], name="upload_logs_status_9638a2_idx"
                    ),
                    models.Index(
                        fields=["attempt_number"], name="upload_logs_attempt_b80059_idx"
                    ),
                    models.Index(
                        fields=["-started_at"], name="upload_logs_started_1382a4_idx"
                    ),
                ],
            },
        ),
    ]
